### ISSUE TITLE
Consider moving the plugin deployment to Maven Central repository

### ISSUE THREAD

**Issue by simonetripodi** [TouK/metatype-exporter-maven-plugin#2]
Guide is well explained on http://central.sonatype.org/pages/ossrh-guide.html

**Comment by alien11689** [comment]
Hi,
plugin is already available at Maven Central:
http://mvnrepository.com/artifact/pl.touk.osgi/metatype-exporter-maven-plugin/1.0.2
README.md is just not updated. // cc @piotrekfus91

**Comment by simonetripodi** [comment]
Awesome! 👍  Thanks for the prompt reply!
